#!/usr/bin/env bash
set -Eeuo pipefail

# verify_audio_e2e.sh
# End-to-end verifier for audio preview + narration endpoints.
# Designed to be adaptable to slightly different FastAPI repos.

ROOT_DIR="${ROOT_DIR:-$(pwd)}"
REPORT_DIR="${REPORT_DIR:-$ROOT_DIR/.verify_audio_e2e}"
REPORT_FILE="$REPORT_DIR/report.txt"
RAW_DIR="$REPORT_DIR/raw"
mkdir -p "$REPORT_DIR" "$RAW_DIR"
: > "$REPORT_FILE"

BASE_URL="${BASE_URL:-http://localhost:8000}"
DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN:-docker compose}"
API_SERVICE="${API_SERVICE:-api}"
WORKER_SERVICE="${WORKER_SERVICE:-worker}"
START_STACK="${START_STACK:-1}"
TAIL_LOG_LINES="${TAIL_LOG_LINES:-150}"

# Auth (optional)
AUTH_ENABLED="${AUTH_ENABLED:-0}"
AUTH_URL="${AUTH_URL:-$BASE_URL/api/v1/auth/login}"
AUTH_METHOD="${AUTH_METHOD:-POST}"
AUTH_EMAIL="${AUTH_EMAIL:-}"
AUTH_PASSWORD="${AUTH_PASSWORD:-}"
AUTH_HEADER_NAME="${AUTH_HEADER_NAME:-Authorization}"
AUTH_HEADER_PREFIX="${AUTH_HEADER_PREFIX:-Bearer }"
AUTH_TOKEN_JQ="${AUTH_TOKEN_JQ:-.access_token // .token // .data.access_token // .data.token}"

# Endpoint candidates. Comma-separated list, first 2xx wins.
PREVIEW_ENDPOINTS="${PREVIEW_ENDPOINTS:-/api/v1/audio/preview,/api/v1/tts/preview,/api/v1/audio/tts/preview}"
NARRATION_ENDPOINTS="${NARRATION_ENDPOINTS:-/api/v1/audio/narration,/api/v1/audio/narration-jobs,/api/v1/narration/jobs,/api/v1/audio/narration/jobs}"
JOB_GET_ENDPOINT_TEMPLATE="${JOB_GET_ENDPOINT_TEMPLATE:-}"

# Payload knobs
VOICE_PROFILE_ID="${VOICE_PROFILE_ID:-test-voice}"
PROJECT_ID="${PROJECT_ID:-test-project}"
PREVIEW_TEXT="${PREVIEW_TEXT:-This is a preview smoke test generated by verify_audio_e2e.sh.}"
NARRATION_TEXT="${NARRATION_TEXT:-This is a narration smoke test with multiple sentences. The goal is to verify that the job is queued, processed by the worker, and results in a playable output.}"
PREVIEW_TIMEOUT="${PREVIEW_TIMEOUT:-35}"
NARRATION_TIMEOUT="${NARRATION_TIMEOUT:-35}"
POLL_SECONDS="${POLL_SECONDS:-3}"
MAX_POLLS="${MAX_POLLS:-20}"

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0
OVERALL_GO=1
TOKEN=""
USED_PREVIEW_ENDPOINT=""
USED_NARRATION_ENDPOINT=""
PREVIEW_URL_FOUND=""
NARRATION_JOB_ID=""
NARRATION_OUTPUT_URL=""

log() {
  printf '%s\n' "$*" | tee -a "$REPORT_FILE"
}

pass() {
  PASS_COUNT=$((PASS_COUNT+1))
  log "[PASS] $*"
}

warn() {
  WARN_COUNT=$((WARN_COUNT+1))
  log "[WARN] $*"
}

fail() {
  FAIL_COUNT=$((FAIL_COUNT+1))
  OVERALL_GO=0
  log "[FAIL] $*"
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "missing required command: $1" >&2; exit 1; }
}

json_get() {
  local file="$1"
  local filter="$2"
  jq -r "$filter // empty" "$file" 2>/dev/null || true
}

trim() {
  awk '{$1=$1;print}'
}

http_request() {
  local method="$1"
  local url="$2"
  local data_file="${3:-}"
  local out_body="$4"
  local out_meta="$5"
  local timeout="${6:-30}"

  local -a curl_args
  curl_args=( -sS -X "$method" "$url" -o "$out_body" -D "$out_meta" --max-time "$timeout" )
  if [[ -n "$TOKEN" ]]; then
    curl_args+=( -H "$AUTH_HEADER_NAME: ${AUTH_HEADER_PREFIX}${TOKEN}" )
  fi
  if [[ -n "$data_file" ]]; then
    curl_args+=( -H "Content-Type: application/json" --data-binary "@$data_file" )
  fi
  curl "${curl_args[@]}" >/dev/null
}

http_code_from_meta() {
  awk 'toupper($1) ~ /^HTTP\// {code=$2} END {print code}' "$1"
}

header_value_from_meta() {
  local header_name="$1"
  local meta_file="$2"
  awk -v IGNORECASE=1 -v key="$header_name" 'BEGIN{FS=":"} tolower($1)==tolower(key){sub(/^ /,"",$2); gsub(/\r/,"",$2); print $2; exit}' "$meta_file"
}

first_working_endpoint() {
  local method="$1"
  local endpoints_csv="$2"
  local data_file="$3"
  local name="$4"

  IFS=',' read -r -a candidates <<< "$endpoints_csv"
  for ep in "${candidates[@]}"; do
    ep="$(printf '%s' "$ep" | trim)"
    [[ -z "$ep" ]] && continue
    local body="$RAW_DIR/${name}_$(basename "$ep" | tr '/' '_').json"
    local meta="$RAW_DIR/${name}_$(basename "$ep" | tr '/' '_').meta"
    if http_request "$method" "$BASE_URL$ep" "$data_file" "$body" "$meta"; then
      local code
      code="$(http_code_from_meta "$meta")"
      if [[ "$code" =~ ^2[0-9][0-9]$ || "$code" == "422" || "$code" == "400" || "$code" == "401" || "$code" == "403" ]]; then
        # 2xx means success; 4xx can still prove route exists, but only accept 2xx as working.
        if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then
          printf '%s\n' "$ep"
          return 0
        fi
      fi
    fi
  done
  return 1
}

maybe_start_stack() {
  if [[ "$START_STACK" != "1" ]]; then
    warn "START_STACK=0, skipping docker compose up"
    return 0
  fi
  if $DOCKER_COMPOSE_BIN up -d >>"$REPORT_FILE" 2>&1; then
    pass "docker stack started"
  else
    fail "docker compose up -d failed"
  fi
}

capture_logs() {
  if $DOCKER_COMPOSE_BIN logs --tail="$TAIL_LOG_LINES" "$API_SERVICE" > "$RAW_DIR/api.logs.txt" 2>&1; then
    pass "captured api logs"
  else
    warn "could not capture api logs"
  fi
  if $DOCKER_COMPOSE_BIN logs --tail="$TAIL_LOG_LINES" "$WORKER_SERVICE" > "$RAW_DIR/worker.logs.txt" 2>&1; then
    pass "captured worker logs"
  else
    warn "could not capture worker logs"
  fi
}

check_ffmpeg() {
  if $DOCKER_COMPOSE_BIN exec -T "$API_SERVICE" ffmpeg -version > "$RAW_DIR/ffmpeg.txt" 2>&1; then
    pass "ffmpeg available in API container"
  else
    fail "ffmpeg missing in API container"
  fi
}

maybe_auth() {
  if [[ "$AUTH_ENABLED" != "1" ]]; then
    warn "AUTH_ENABLED=0, skipping auth"
    return 0
  fi
  if [[ -z "$AUTH_EMAIL" || -z "$AUTH_PASSWORD" ]]; then
    fail "AUTH_ENABLED=1 but AUTH_EMAIL/AUTH_PASSWORD missing"
    return 1
  fi
  local auth_payload="$RAW_DIR/auth_request.json"
  cat > "$auth_payload" <<JSON
{"email":"$AUTH_EMAIL","password":"$AUTH_PASSWORD"}
JSON
  local body="$RAW_DIR/auth_response.json"
  local meta="$RAW_DIR/auth_response.meta"
  if http_request "$AUTH_METHOD" "$AUTH_URL" "$auth_payload" "$body" "$meta" 20; then
    local code
    code="$(http_code_from_meta "$meta")"
    if [[ "$code" =~ ^2[0-9][0-9]$ ]]; then
      TOKEN="$(json_get "$body" "$AUTH_TOKEN_JQ")"
      if [[ -n "$TOKEN" ]]; then
        pass "auth token acquired"
      else
        fail "auth succeeded but token not found with AUTH_TOKEN_JQ=$AUTH_TOKEN_JQ"
      fi
    else
      fail "auth failed with HTTP $code"
    fi
  else
    fail "auth request failed"
  fi
}

build_preview_payload() {
  local f="$RAW_DIR/preview_request.json"
  cat > "$f" <<JSON
{
  "text": "$PREVIEW_TEXT",
  "voice_profile_id": "$VOICE_PROFILE_ID",
  "provider": "elevenlabs"
}
JSON
  printf '%s\n' "$f"
}

build_narration_payload() {
  local f="$RAW_DIR/narration_request.json"
  cat > "$f" <<JSON
{
  "project_id": "$PROJECT_ID",
  "voice_profile_id": "$VOICE_PROFILE_ID",
  "text": "$NARRATION_TEXT",
  "segments": [
    {"text": "Segment one for narration verification."},
    {"text": "Segment two for narration verification."},
    {"text": "Segment three for narration verification."}
  ]
}
JSON
  printf '%s\n' "$f"
}

verify_preview() {
  local payload="$1"
  USED_PREVIEW_ENDPOINT="$(first_working_endpoint POST "$PREVIEW_ENDPOINTS" "$payload" "preview")" || true
  if [[ -z "$USED_PREVIEW_ENDPOINT" ]]; then
    fail "could not find a working preview endpoint from PREVIEW_ENDPOINTS=$PREVIEW_ENDPOINTS"
    return 1
  fi

  local body="$RAW_DIR/preview_final_body.json"
  local meta="$RAW_DIR/preview_final_meta.txt"
  if ! http_request POST "$BASE_URL$USED_PREVIEW_ENDPOINT" "$payload" "$body" "$meta" "$PREVIEW_TIMEOUT"; then
    fail "preview request failed at $USED_PREVIEW_ENDPOINT"
    return 1
  fi
  local code
  code="$(http_code_from_meta "$meta")"
  if [[ ! "$code" =~ ^2[0-9][0-9]$ ]]; then
    fail "preview endpoint returned HTTP $code"
    return 1
  fi

  PREVIEW_URL_FOUND="$(json_get "$body" '.preview_url // .url // .data.preview_url // .data.url')"
  local storage_key
  storage_key="$(json_get "$body" '.preview_storage_key // .storage_key // .data.preview_storage_key')"
  if [[ -n "$PREVIEW_URL_FOUND" ]]; then
    pass "preview returned preview_url"
  else
    fail "preview response missing preview_url"
  fi
  if [[ -n "$storage_key" ]]; then
    pass "preview returned storage key"
  else
    warn "preview response missing preview_storage_key"
  fi
}

extract_job_id_and_output() {
  local body="$1"
  NARRATION_JOB_ID="$(json_get "$body" '.job_id // .id // .data.job_id // .data.id')"
  NARRATION_OUTPUT_URL="$(json_get "$body" '.output_url // .final_output_url // .data.output_url // .data.final_output_url')"
}

build_job_url() {
  local job_id="$1"
  if [[ -n "$JOB_GET_ENDPOINT_TEMPLATE" ]]; then
    printf '%s\n' "${JOB_GET_ENDPOINT_TEMPLATE//\{job_id\}/$job_id}"
    return 0
  fi
  printf '%s\n' "/api/v1/audio/narration/$job_id"
}

poll_narration_job() {
  local job_id="$1"
  local job_ep
  job_ep="$(build_job_url "$job_id")"

  for ((i=1; i<=MAX_POLLS; i++)); do
    local body="$RAW_DIR/narration_poll_${i}.json"
    local meta="$RAW_DIR/narration_poll_${i}.meta"
    if ! http_request GET "$BASE_URL$job_ep" "" "$body" "$meta" 20; then
      warn "poll $i failed for job $job_id"
      sleep "$POLL_SECONDS"
      continue
    fi
    local code
    code="$(http_code_from_meta "$meta")"
    if [[ ! "$code" =~ ^2[0-9][0-9]$ ]]; then
      warn "poll $i returned HTTP $code for job $job_id"
      sleep "$POLL_SECONDS"
      continue
    fi
    local status
    status="$(json_get "$body" '.status // .data.status')"
    local out
    out="$(json_get "$body" '.output_url // .final_output_url // .data.output_url // .data.final_output_url')"
    if [[ -n "$out" ]]; then
      NARRATION_OUTPUT_URL="$out"
    fi
    case "$status" in
      succeeded|completed|done)
        pass "narration job reached success state: $status"
        return 0
        ;;
      failed|error|cancelled)
        fail "narration job entered terminal bad state: $status"
        return 1
        ;;
      queued|pending|processing|running|'')
        sleep "$POLL_SECONDS"
        ;;
      *)
        warn "narration job has unrecognized status: $status"
        sleep "$POLL_SECONDS"
        ;;
    esac
  done
  fail "narration polling timed out after $MAX_POLLS polls"
  return 1
}

verify_narration() {
  local payload="$1"
  USED_NARRATION_ENDPOINT="$(first_working_endpoint POST "$NARRATION_ENDPOINTS" "$payload" "narration")" || true
  if [[ -z "$USED_NARRATION_ENDPOINT" ]]; then
    fail "could not find a working narration endpoint from NARRATION_ENDPOINTS=$NARRATION_ENDPOINTS"
    return 1
  fi

  local body="$RAW_DIR/narration_final_body.json"
  local meta="$RAW_DIR/narration_final_meta.txt"
  if ! http_request POST "$BASE_URL$USED_NARRATION_ENDPOINT" "$payload" "$body" "$meta" "$NARRATION_TIMEOUT"; then
    fail "narration request failed at $USED_NARRATION_ENDPOINT"
    return 1
  fi
  local code
  code="$(http_code_from_meta "$meta")"
  if [[ ! "$code" =~ ^2[0-9][0-9]$ ]]; then
    fail "narration endpoint returned HTTP $code"
    return 1
  fi

  extract_job_id_and_output "$body"
  if [[ -n "$NARRATION_JOB_ID" ]]; then
    pass "narration returned job id: $NARRATION_JOB_ID"
    poll_narration_job "$NARRATION_JOB_ID" || true
  else
    warn "narration response missing job_id; checking inline output instead"
  fi

  if [[ -n "$NARRATION_OUTPUT_URL" ]]; then
    pass "narration returned output url"
  else
    fail "narration did not produce output_url"
  fi
}

verify_worker_logs() {
  if [[ ! -f "$RAW_DIR/worker.logs.txt" ]]; then
    warn "worker logs not available for inspection"
    return 0
  fi
  if grep -Eiq 'narration|voice_clone|audio_mix|ffmpeg|concat' "$RAW_DIR/worker.logs.txt"; then
    pass "worker logs contain audio processing signals"
  else
    warn "worker logs do not show obvious audio processing signals"
  fi
}

download_and_probe_output() {
  local url="$1"
  [[ -z "$url" ]] && { fail "no output url to probe"; return 1; }
  local out="$RAW_DIR/final_output.bin"
  if curl -sS -L --max-time 45 "$url" -o "$out"; then
    if [[ -s "$out" ]]; then
      pass "downloaded final audio output"
    else
      fail "downloaded output file is empty"
      return 1
    fi
  else
    fail "could not download final output url"
    return 1
  fi

  if command -v ffprobe >/dev/null 2>&1; then
    if ffprobe -v error -show_format -show_streams "$out" > "$RAW_DIR/final_output.ffprobe.txt" 2>&1; then
      pass "ffprobe validated final audio output"
    else
      fail "ffprobe could not validate final audio output"
    fi
  else
    warn "ffprobe not available on host; skipping output probe"
  fi
}

print_summary() {
  log ""
  log "===== SUMMARY ====="
  log "BASE_URL=$BASE_URL"
  log "PREVIEW_ENDPOINT=$USED_PREVIEW_ENDPOINT"
  log "NARRATION_ENDPOINT=$USED_NARRATION_ENDPOINT"
  log "NARRATION_JOB_ID=$NARRATION_JOB_ID"
  log "PREVIEW_URL_FOUND=${PREVIEW_URL_FOUND:-<empty>}"
  log "NARRATION_OUTPUT_URL=${NARRATION_OUTPUT_URL:-<empty>}"
  log "PASS_COUNT=$PASS_COUNT"
  log "WARN_COUNT=$WARN_COUNT"
  log "FAIL_COUNT=$FAIL_COUNT"
  if [[ "$OVERALL_GO" == "1" ]]; then
    log "RESULT=GO"
    printf 'GO\n'
  else
    log "RESULT=NO-GO"
    printf 'NO-GO\n'
  fi
}

main() {
  need_cmd curl
  need_cmd jq
  need_cmd python

  log "verify_audio_e2e.sh starting"
  log "ROOT_DIR=$ROOT_DIR"
  log "REPORT_DIR=$REPORT_DIR"
  maybe_start_stack
  capture_logs
  check_ffmpeg
  maybe_auth || true

  local preview_payload narration_payload
  preview_payload="$(build_preview_payload)"
  narration_payload="$(build_narration_payload)"

  verify_preview "$preview_payload" || true
  verify_narration "$narration_payload" || true
  capture_logs
  verify_worker_logs
  if [[ -n "$NARRATION_OUTPUT_URL" ]]; then
    download_and_probe_output "$NARRATION_OUTPUT_URL" || true
  fi
  print_summary

  if [[ "$OVERALL_GO" != "1" ]]; then
    exit 1
  fi
}

main "$@"
