"""add_audio_job_idempotency_key

Revision ID: f4b28e2666cf
Revises: 180bf7c48e34
Create Date: 2026-04-25 19:37:59.158376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b28e2666cf'
down_revision: Union[str, Sequence[str], None] = '180bf7c48e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('idempotency_key', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_audio_jobs_idempotency_key'), 'audio_jobs', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_jobs_idempotency_key'), table_name='audio_jobs')
    op.drop_column('audio_jobs', 'idempotency_key')
    # ### end Alembic commands ###
